ignore:
  #  - Bean.groovy
  - nul.groovy

trigger:
  name: shell
  type: path

bean:
  - Bean.groovy

# shelve TODO next
#except:
#  - name: demo.groovy
#    trigger: scheduler
#  - name: demo.asj
#    trigger: mq
