iotaki:
  aggron:
    github:
      uri: https://github.com/theoxao/iotaki
      path: pokeball/src/main/resources/script
      branch: master
spring:
  ktor:
    port:9999
  aop:
    proxy-target-class: true
  rabbitmq:
    username: admin
    password: 123456
